#!/bin/bash

# TODO: Unpin dask-labextension version once extensions have been made compatibility updates
jupyter labextension install --no-build dask-labextension@1.1.0

# Install extension that supports '%matplotlib widget'.
jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager
jupyter labextension install --no-build jupyter-matplotlib

# We deferred building above (--no-build) to do it just once here.
jupyter lab build
